### ISSUE TITLE
"Unable to connect to the service" 

### ISSUE THREAD

**Issue by GordoPitudo** [Egoistically/ALAuto#113]
before the update it worked correctly, I have root activated, the configuration as before. Does anyone know what the problem is ?
 https://gyazo.com/4ab22f2feb68ca16066455aeb76b16e8
https://gyazo.com/0137a4ea507c8dd6353536d1dda74d65

**Comment by hjk22** [comment]
Your `Service` setting is incorrect since you are keeping the `IP` word in the value field.
It should be `Service: 127.0.0.1:31200`.
If your configuration was always like this, the bot was able to connect to your emulator because it got automatically attached to the adb daemon and a less strict check was done.
