### ISSUE TITLE
Ink-Stained Steel Sakura Event Maps Not Found

### ISSUE THREAD

**Issue by mbarcelon** [Egoistically/ALAuto#153]
![image](https://user-images.githubusercontent.com/65305358/87862829-3bf1e100-c922-11ea-82ad-c6136bbd1fb7.png)

Seems like it affects E-A1 to E-B1 so far. Here is my config settings:

...
[Updates]
Enabled: True
Channel: Development

[Assets]
Server: EN

[Combat]
Enabled: True
Map: E-B1
KillsBeforeBoss: 0
BossFleet: True
OilLimit: 8000
RetireCycle: 1
RetreatAfter: 0
IgnoreMysteryNodes: False
FocusOnMysteryNodes: False
ClearingMode: False
HideSubsHuntingRange: False
SmallBossIcon: False
SirenElites: False
IgnoreMorale: False
LowMoodSleepTime: 1
SearchMode: 1

[Headquarters]
Dorm: False
Academy: False
SkillBookTier: 2
AvailableSupplies: 5000 3000 2000 1000

[Modules]
Commissions: False
Missions: False

[Enhancement]
Enabled: False
SingleEnhancement: False

[Retirement]
Enabled: True
Rares: True
Commons: True

...

**Comment by martbarc** [comment]
Issue solved, please delete issue thanks!

**Comment by aodpip** [comment]
What did you do to fix this? I have the same issue with B2.

**Comment by martbarc** [comment]
> What did you do to fix this? I have the same issue with B2.

@aodpip In **combat.py** change these values to the ones listed below _(lines 260-266)_:
```python
        Utils.wait_update_screen()
        map_region = Utils.find('maps/map_{}'.format(self.chapter_map), 0.96)
        if map_region == None:
            Logger.log_error("Cannot find the specified map, please move to the world where it's located.")
        while map_region == None:
            map_region = Utils.find('maps/map_{}'.format(self.chapter_map), 0.96)
            Utils.wait_update_screen(1)
```
I believe the reason having a lower value than 0.99 in "Utils.find('maps/map_{}'.format(self.chapter_map), **0.99**)" lets the program see the event map number image through the flowers in the sakura event.

**Comment by aodpip** [comment]
> > What did you do to fix this? I have the same issue with B2.
> 
> @aodpip In **combat.py** change these values to the ones listed below _(lines 260-266)_:
> 
> ```python
>         Utils.wait_update_screen()
>         map_region = Utils.find('maps/map_{}'.format(self.chapter_map), 0.96)
>         if map_region == None:
>             Logger.log_error("Cannot find the specified map, please move to the world where it's located.")
>         while map_region == None:
>             map_region = Utils.find('maps/map_{}'.format(self.chapter_map), 0.96)
>             Utils.wait_update_screen(1)
> ```
> 
> I believe the reason having a lower value than 0.99 in "Utils.find('maps/map_{}'.format(self.chapter_map), **0.99**)" lets the program see the event map number image through the flowers in the sakura event.

I have just done done this change and that seems to fix the issue where it can't find the map but now it just keeps searching the map and doesn't select an enemy to battle.

**Comment by martbarc** [comment]
> I have just done done this change and that seems to fix the issue where it can't find the map but now it just keeps searching the map and doesn't select an enemy to battle.

@aodpip Try setting your config **SearchMode: 0**. 

From wiki:
SearchMode: Specify which search method the bot will employ. Allowed values are 0 and 1.
0: The bot searches for the triangles which represent the enemy type and for the level, the coordinates obtained are then translated, in order to point to the center of the cell. This means that an enemy is picked up as long as its type or its level are visible. The downside is that this option is heavier (since the bot will also search with resized assets) and it's more susceptible to false positives when the similarity threshold is lowered.
1: The bot searches for the triangles which represent the enemy type and for the level: for each finding a rectangle is drawn. An enemy is recognized as such if there is an intersection between a rectangle drawn from the enemy type and one drawn from the level: the center of this intersection is the enemy's coordinates. This improves the reliability and the performance of enemies' search. The downside is that both the triangles and the level must be visible for an enemy to be picked up.
Default: 1.
