### ISSUE TITLE
Works great on Windows 7 64bit with LDPlayer

### ISSUE THREAD

**Issue by Heavedistant** [Egoistically/ALAuto#2]
First of all thank you for sharing and updating this amazing script. I've got it running on Windows 7 64bit with [LDPlayer](https://www.ldplayer.net/) 1920x1080 resolution, 30fps, Android 5.1.1, Python 3.4.7 and the ADB and SED links provided.

I did have to take one extra step after installing the requirements.txt. For some reason the opencv module threw an error until I ran `pip3 install opencv-contrib-python`. Now it's working great, maybe its a Windows 7 thing.

Also noticed the script would hang on the Auto Combat Alert popup which I thought I had turned off. Maybe something to add to the Readme to make sure it's turned off.

Thank you for this huge improvement in grinding 3-4 and I'm sure many more. I got Akagi but still need to get that Kaga!

**Comment by Egoistically** [comment]
It also happened to me yesterday when I forgot about it. Haven't fixed it yet because after all it only happens on your first combat after starting the game. Will look into it later though.

That aside, thank you very much for your kind words. I really appreciate them and I'm glad the bot has been useful for you.
Here you have my Discord if you wanna message me anytime: ego#9459.

Have a great day!
P.S. Good luck in getting Kaga.

**Comment by Egoistically** [comment]
Should be fixed now https://github.com/Egoistically/ALAuto/commit/7a14e6b1f18abe2c9ee45bcd97d236e1fb3b215b.

**Comment by Heavedistant** [comment]
Wow that was a quick update, thank you. It's generous of you to update the scripts and share this working version. Still no Kaga yet but it's gotta drop sooner or later!
