### ISSUE TITLE
in event map B2 B4 has problem

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#25]
B4

> it's  large map and CV2 fail or miss location scan. and fail to go boss node.

![image](https://user-images.githubusercontent.com/29043573/68537372-f5acb100-0394-11ea-907c-46216cf05e17.png)

B2

> location [1141, 969] is button Retreat and scripts auto click at thst point.

![image](https://user-images.githubusercontent.com/29043573/68537397-6d7adb80-0395-11ea-80b3-50702506b406.png)

**Comment by Egoistically** [comment]
![image](https://user-images.githubusercontent.com/55348950/68537430-b2861a00-0363-11ea-91a4-53aed2a4444e.png)

Those maps need other assets to match the zoom (either new files or resizing current ones), since the event is ending in ~72 hours I think it's kind of pointless to work on it at this point.
Please stick to event maps with normal zoom and sorry for the inconvenience.

**Comment by Walofz** [comment]
oh sorry i miss to read patch note.
