### ISSUE TITLE
More script is broken & Loop after update patch.

### ISSUE THREAD

**Issue by Walofz** [Egoistically/ALAuto#57]
![image](https://user-images.githubusercontent.com/29043573/72067280-e86c5e00-3314-11ea-89b1-b9c505f5b316.png)

Work only Combat

Don't work
- Commission
- Skill Book Update (Sry for sort skill) 
- Retire ship

**Comment by Egoistically** [comment]
They love unnecessarily changing assets, fixed https://github.com/Egoistically/ALAuto/commit/2fde53f33d417e6e6bc36a84218ade9c724e1ad1.

**Comment by Egoistically** [comment]
Screwed up on that update, now it should be fixed https://github.com/Egoistically/ALAuto/commit/6be1ed1603c47529181bfb3aeb188bd5d205b45f.

**Comment by JustShinobi** [comment]
maybe need change assets for retirement too?

stuck here.

![](https://f.cyberdrop.cc/ConEmu64_2020-01-09_17-53-46-RNI48Sjl.png)

![](https://f.cyberdrop.cc/Bluestacks_2020-01-09_17-54-44-mR9yAKFQ.png)

**Comment by Egoistically** [comment]
Yeah... Fuck my life https://github.com/Egoistically/ALAuto/commit/1f4d3d5961c89a02c7a1384e95a043cca2e80ae4.

**Comment by hjk22** [comment]
> Don't work
> 
> * Commission
> * Skill
> * Retire ship

What do you mean by skill not working? The skill levelling module worked fine in the bot run that I started.

**Comment by Walofz** [comment]
> > Don't work
> > 
> > * Commission
> > * Skill
> > * Retire ship
> 
> What do you mean by skill not working? The skill levelling module worked fine in the bot run that I started.

Sry i mean Update skill ship, i set use T1 Book but script don't work and stuck at select book screen.

![image](https://user-images.githubusercontent.com/29043573/72114624-c73c5980-3376-11ea-9cd4-4bc39186eeb6.png)

**Comment by hjk22** [comment]
Ok, now I understand. The issue doesn't depend on the new patch, but because you already used up all the offensive T3 and T2 skillbooks. I didn't know that once they were used up they would disappear from the skillbook selection menu. I will need to rethink how to implement the skill levelling module taking this into consideration; I will fix this in the next few days. Right now you can't use this module unless you get a copy of both T2 and T3 offensive skillbook, but you're in luck since you can farm those tomorrow.

**Comment by Walofz** [comment]
Ah, Thx you @hjk22

**Comment by hjk22** [comment]
@Walofz now it should be fixed.

**Comment by Walofz** [comment]
@hjk22 Thx you.
